const config = {

  "socials" : [
  { name: "email", link: "mailto:team@rowdyhacks.org" },
  { name: "instagram", link: "https://www.instagram.com/rowdyhacks/" },
  { name: "linkedin", link: "https://www.linkedin.com/company/rowdyhacks" },
  { name: "github", link: "https://github.com/acmutsa" },
  { name: "discord", link: "https://discord.gg/nGGVr5gpP" },
  { name: "youtube", link: "https://www.youtube.com/@acmutsa" }
],

  "hackathons": [
  {
    number: 0,
    name: "RowdyHacks I",
    year: 2016,
    iteration: "I",
    description: "Small event description. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis.",
    imgFormat: "svg",
    photosLink: "#",
  },
  {
    number: 1,
    name: "RowdyHacks II",
    year: 2017,
    iteration: "II",
    description: "Small event description. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis.",
    imgFormat: "svg",
    photosLink: "#",
  },
  {
    number: 2,
    name: "RowdyHacks III",
    year: 2018,
    iteration: "III",
    description: "Small event description. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis.",
    imgFormat: "svg",
    photosLink: "#",
  },
  {
    number: 3,
    name: "RowdyHacks IV",
    year: 2019,
    iteration: "IV",
    description: "Small event description. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis.",
    imgFormat: "svg",
    photosLink: "#",
  },
  {
    number: 4,
    name: "RowdyHacks V",
    year: 2020,
    iteration: "V",
    description: "Small event description. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "afcs", 
      "att",
      "civ-tech-sa",
      "cnf", 
      "frost-bank", 
      "google-geo",
      "google", 
      "heb", 
      "i-heart-media",
      "man-tech",
      "mlh",
      "nerd-focus",
      "nsa",
      "paycom", 
      "popcorn-piccadilly",
      "posh",
      "sticker",
      "tech-data",
      "tiffs-treat",
      "twilio",
      "usaa",
      "utsa-cos", 
      "utsa-cs", 
      "utsa-iscs",
      "utsa-nscc",
      "utsa-research",
      "utsa-sds",
      "valero",
      "web-head"
    ]
  },
  {
    number: 5,
    name: "RowdyHacks VI",
    year: 2021,
    iteration: "VI",
    description: "Small event description. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "accenture",
      "civ-tech-sa",
      "frost-bank",
      "hcl",
      "heb",
      "mlh",
      "nsa",
      "pwc",
      "tech-data",
      "the-codex",
      "utsa-career-center",
      "utsa-cos",
      "utsa-cs",
      "utsa-engineering",
      "utsa-iscs",
      "utsa-sds",
    ]
  },
  {
    number: 6,
    name: "RowdyHacks VII",
    year: 2022,
    iteration: "VII",
    description: "Small event description. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "acm",
      "ara", 
      "assembly-ai",  
      "frost-bank", 
      "google", 
      "heb", 
      "interview-cake",
      "klesse", 
      "makerspace", 
      "mitre",
      "mlh",
      "paycom", 
      "sticker", 
      "td-synnex", 
      "utsa-cos", 
      "utsa-cos-scc", 
      "valero",
      "wolfram"
    ]
  },
  {
    number: 7,
    name: "RowdyHacks VIII",
    year: 2023,
    iteration: "VIII",
    description: "Small event description. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis.",
    imgFormat: "svg",
    photosLink: "#",
  },
  {
    number: 8,
    name: "RowdyHacks IX",
    iteration: "IX",
    year: 2024,
    description: "Small event description. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "accenture", 
      "acm",
      "afcs", 
      "artea", 
      "bunz", 
      "codepath", 
      "cymanii", 
      "dell", 
      "frost-bank", 
      "google", 
      "heb", 
      "klesse", 
      "marathon-oil", 
      "paycom", 
      "pho", 
      "rowdy-tech", 
      "six-flags", 
      "students-and-startups", 
      "swivel", 
      "td-synnex", 
      "utsa-cos", 
      "utsa-cs", 
      "utsa-data-science",
      "valero",
      "wolfram"
    ]
  },
  {
    number: 9,
    name: "RowdyHacks X",
    iteration: "X",
    year: 2024,
    description: "Small event description. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "cymanii", 
      "dell", 
      "groq", 
      "heb", 
      "klesse", 
      "matrix", 
      "schroeder", 
      "swivel", 
      "utsa-cs", 
      "utsa-data-science"
    ]
  },
  {
    number: 10,
    name: "RowdyHacks XI",
    year: 2025,
    iteration: "XI",
    description: "Small event description. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "caicc", 
      "dell", 
      "heb", 
      "schroeder", 
      "swivel", 
      "union-pacific", 
      "utsa-cs", 
      "yahoo"
    ]
  },
  {
    number: 11,
    name: "RowdyHacks XII",
    year: 2026,
    iteration: "XII",
    description: "Small event description. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: []
  }
]

};

export default config;
