const config = {

  "socials" : [
  { name: "email", link: "mailto:team@rowdyhacks.org" },
  { name: "instagram", link: "https://www.instagram.com/rowdyhacks/" },
  { name: "linkedin", link: "https://www.linkedin.com/company/rowdyhacks" },
  { name: "github", link: "https://github.com/acmutsa" },
  { name: "discord", link: "https://discord.gg/nGGVr5gpP" },
  { name: "youtube", link: "https://www.youtube.com/@acmutsa" }
],

  "hackathons": [
  {
    number: 0,
    name: "RowdyHacks I",
    year: 2016,
    iteration: "I",
    description: "The one that started it all: a scrappy weekend of caffeine, code, and questionable robot creations. It planted the seed for what would become a UTSA tradition.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "amazon-alexa",
      "code-jam",
      "promoter",
      "usaa"
    ]
  },
  {
    number: 1,
    name: "RowdyHacks II",
    year: 2017,
    iteration: "II",
    description: "Round two proved RowdyHacks wasn't a fluke. More hackers showed up, chasing bigger ideas and only slightly better sleep schedules than year one.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "amazon-alexa",
      "code-jam",
      "promoter",
      "utsa-cs"
    ]
  },
  {
    number: 2,
    name: "RowdyHacks III",
    year: 2018,
    iteration: "III",
    description: "Three's a trend. More hardware, more caffeine, and a whole lot more 3 a.m. debugging sessions fueled by pure stubbornness.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "acm",
      "afcs", 
      "cox-automotive",
      "geekdom",
      "infosys",
      "medcom",
      "motiva",
      "usaa"
    ]
  },
  {
    number: 3,
    name: "RowdyHacks IV",
    year: 2019,
    iteration: "IV",
    description: "RowdyHacks IV rolled in with roman numeral swagger, proving that great ideas (and great chaos) only get better with practice.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "accenture", 
      "acm-w",
      "acm",
      "afcs", 
      "amazon-alexa",
      "chevron", 
      "code-jam",
      "cox-automotive",
      "geekdom",
      "infosys",
      "medcom",
      "motiva",
      "promoter",
      "usaa",
      "utsa-cs"
    ]
  },
  {
    number: 4,
    name: "RowdyHacks V",
    year: 2020,
    iteration: "V",
    description: "Five years in, RowdyHacks got creative and kept the hacking spirit alive no matter what the world threw at it. Turns out great ideas don't need a pause button.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "afcs", 
      "att",
      "civ-tech-sa",
      "cnf", 
      "frost-bank", 
      "google-geo",
      "google", 
      "heb", 
      "i-heart-media",
      "man-tech",
      "mlh",
      "nerd-focus",
      "nsa",
      "paycom", 
      "popcorn-piccadilly",
      "posh",
      "sticker",
      "tech-data",
      "tiffs-treat",
      "twilio",
      "usaa",
      "utsa-cos", 
      "utsa-cs", 
      "utsa-iscs",
      "utsa-nscc",
      "utsa-research",
      "utsa-sds",
      "valero",
      "web-head"
    ]
  },
  {
    number: 5,
    name: "RowdyHacks VI",
    year: 2021,
    iteration: "VI",
    description: "Back and better, RowdyHacks VI welcomed hackers back to the grind with fresh energy and an even longer sponsor list.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "accenture",
      "civ-tech-sa",
      "frost-bank",
      "hcl",
      "heb",
      "mlh",
      "nsa",
      "pwc",
      "tech-data",
      "the-codex",
      "utsa-career-center",
      "utsa-cos",
      "utsa-cs",
      "utsa-engineering",
      "utsa-iscs",
      "utsa-sds",
    ]
  },
  {
    number: 6,
    name: "RowdyHacks VII",
    year: 2022,
    iteration: "VII",
    description: "Lucky number seven brought sharper projects, sharper pitches, and a room full of impressively caffeinated overachievers.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "acm",
      "ara", 
      "assembly-ai",  
      "frost-bank", 
      "google", 
      "heb", 
      "interview-cake",
      "klesse", 
      "makerspace", 
      "mitre",
      "mlh",
      "paycom", 
      "sticker", 
      "td-synnex", 
      "utsa-cos", 
      "utsa-cos-scc", 
      "valero",
      "wolfram"
    ]
  },
  {
    number: 7,
    name: "RowdyHacks VIII",
    year: 2023,
    iteration: "VIII",
    description: "RowdyHacks VIII hit peak chaos-in-the-best-way, packing the room with builders determined to out-hack their own to-do lists.",
    imgFormat: "svg",
    photosLink: "#",
  },
  {
    number: 8,
    name: "RowdyHacks IX",
    iteration: "IX",
    year: 2024,
    description: "Nine editions deep and still going strong, RowdyHacks IX proved that great hackathons only get louder with age.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "accenture", 
      "acm",
      "afcs", 
      "artea", 
      "bunz", 
      "codepath", 
      "cymanii", 
      "dell", 
      "frost-bank", 
      "google", 
      "heb", 
      "klesse", 
      "marathon-oil", 
      "paycom", 
      "pho", 
      "rowdy-tech", 
      "six-flags", 
      "students-and-startups", 
      "swivel", 
      "td-synnex", 
      "utsa-cos", 
      "utsa-cs", 
      "utsa-data-science",
      "valero",
      "wolfram"
    ]
  },
  {
    number: 9,
    name: "RowdyHacks X",
    iteration: "X",
    year: 2024,
    description: "Double digits! RowdyHacks X celebrated a decade of code and community with hackers who refused to sleep before demo day.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "cymanii", 
      "dell", 
      "groq", 
      "heb", 
      "klesse", 
      "matrix", 
      "schroeder", 
      "swivel", 
      "utsa-cs", 
      "utsa-data-science"
    ]
  },
  {
    number: 10,
    name: "RowdyHacks XI",
    year: 2025,
    iteration: "XI",
    description: "RowdyHacks XI showed up with new sponsors, new ideas, and the same old promise: come for the hacking, stay for the free swag.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: [
      "caicc", 
      "dell", 
      "heb", 
      "schroeder", 
      "swivel", 
      "union-pacific", 
      "utsa-cs", 
      "yahoo"
    ]
  },
  {
    number: 11,
    name: "RowdyHacks XII",
    year: 2026,
    iteration: "XII",
    description: "RowdyHacks XII is gearing up to be the biggest one yet, so grab your laptop and a wildly irresponsible amount of energy drinks.",
    imgFormat: "png",
    photosLink: "#",
    sponsors: []
  }
]

};

export default config;
